### ISSUE TITLE
Period-over-Period Overlay

### ISSUE THREAD

**Issue by ahazanov** [sneaky-emily/wowtoken.app#11]
Thank you for publishing this tool - it's a pleasure to use; refreshingly slick and streamlined.  (And the blog entries were fun to read too.)

I would like to request the ability to overlay the graph for the current period with the graph of the previous period (week-over-week, month-over-month, etc.).  This should make it easier to see seasonality patterns and help predict where the price might go next.

It might also be nice to overlay not just the previous period, but to be able to choose which past period to use (e.g., previous week  / same week of the previous month / same week a year ago / etc.), though I can see how this might over-complicate the UI.

Either way, there are some interesting choices about how best to align the data depending on the graph period, how to style the graph for clarity, how to handle the tooltip, etc.

**Comment by sneaky-emily** [comment]
Hi there! Thank you for the kind words! It always makes me happy to know others find use out of my tool and enjoy my engineering write ups (I am due for another one soon as there have been a number of changes recently). 

As far as your feature request, it sounds like an excellent idea that I would be happy to work on. It will very likely require some backend changes to accommodate more arbitrary date requests, so it wont be super fast, but I have a week off of work the week of the 28th, so I should have a lot of free time to implement this and would expect it to be implemented and live by the end of that week or soon after. I'll make sure to keep this issue updated with progress as I implement it.

**Comment by sneaky-emily** [comment]
Hi, with commit d25334d35f0bf443a0104c3dc6fa68d67bf2be78 this functionality has now been implemented, and can be found under the "Advance Charting Options" section of the site. It should work with all time selections except "All Available", for which it will be disabled if selected. This will be ported to the classic site over the next week.

You may have to force-refresh your cache (Ctl-Shift-R/Cmd-Shift-R) to get the newest version of the site with this functionality. This is an MVP, and there is some things I should clean up in the future, but that will be part of refactoring older sections of the original code. ChartJS has some limitations I have to work around, but based on some comparisons to other sites that display period-over-period functionality the UX and UI is roughly the same. 
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/21a30768-31af-4867-9ad7-559af5d049ab">

**Comment by ahazanov** [comment]
That's awesome, thank you so much!
